### ISSUE TITLE
Integrate the formatter into OpenScad itself

### ISSUE THREAD

**Issue by besi** [Maxattax97/openscad-format#4]
Have you considered working together with the guys at openscad and ideally build your tool into the editor?

**Comment by besi** [comment]
The need seems to be present. 
I came across this post, where someone was looking for a formatter. I don't have an account.

http://forum.openscad.org/quot-lint-quot-like-support-for-OpenSCAD-td25712.html

**Comment by Maxattax97** [comment]
The [OpenSCAD](https://github.com/openscad/openscad) editor is written largely in C++. Be my guest if you want to reach out to their team, but since this is all Javascript, I highly doubt they'd want to integrate it directly into the editor. Though your sentiment is kind.
