### ISSUE TITLE
Installation dependencies

### ISSUE THREAD

**Issue by besi** [Maxattax97/openscad-format#5]
I had some trouble installing the openscad-format package.

I did this to install this:

    # I am not sure if this first step was required but it kept asking for different dependencies
    npm uninstall openscad-format  eslint-config-airbnb-base  

    npm install -g eslint-config-airbnb-base@^13.1.0  eslint@^4.19.1 eslint-plugin-import@^2.17.2 openscad-format   

Would it be possible that the openscad-format installs all required dependencies automatically and does not issue any warnings

**Comment by Maxattax97** [comment]
These are due to [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) for dev modules, you can safely ignore those warnings.

![image](https://user-images.githubusercontent.com/4708067/73940930-524b3980-48ba-11ea-94b4-964919cda84d.png)
