### ISSUE TITLE
Modules not consistently formatted

### ISSUE THREAD

**Issue by besi** [Maxattax97/openscad-format#6]
I have the following snipped in my formatted `scad` file:

```scad
module dxf(layer)
{
    import(file = "makercase-50-30-105-inside-3-5mm-thickness.dxf",
           layer = layer);
}

module
back()
{
    linear_extrude(height = thickness, center = true) difference()
    {
        dxf("back_outsideCutPath", 0); // , - outer_height - spacing
        plug_radius = 3.5;
        translate([
            outer_width / 2,
            outer_height + spacing / 2 * 2 + outer_height / 2
        ]) circle(plug_radius, $fn = 20);
    }
}
```

Please note that the first module is one one line whereas all following modules are written on two lines.

**Comment by Maxattax97** [comment]
This is an issue relating to Clang itself. You'll have to alter your `.openscad-format` file to get it to do what you want.

https://clang.llvm.org/docs/ClangFormatStyleOptions.html
